version: "3.4"
services:
  dynamodb:
    image: deangiberson/aws-dynamodb-local
    ports:
      - 8000:8000
    expose:
      - 8000
  gofish:
    build: .
    depends_on:
      - dynamodb
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - AWS_DEFAULT_REGION=ap-nil-1
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
